/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      colors: {
        'surface-default':         'var(--color-black)',
        'surface-subtle':          'var(--color-gray-950)',
        'surface-raised':          'var(--color-gray-800)',
        'surface-elevated':        'var(--color-gray-700)',
        'surface-overlay':         'var(--color-gray-600)',
        'content-primary':         'var(--color-white)',
        'content-secondary':       'var(--color-gray-400)',
        'content-muted':           'var(--color-gray-500)',
        'content-inverse':         'var(--color-black)',
        'content-accent':          'var(--color-slate-300)',
        'line-default':            'var(--color-gray-700)',
        'line-subtle':             'var(--color-gray-800)',
        'line-strong':             'var(--color-gray-600)',
        'action-primary':          'var(--color-slate-500)',
        'action-primary-hover':    'var(--color-slate-300)',
        'action-primary-text':     'var(--color-white)',
        'action-secondary':        'var(--color-gray-700)',
        'action-secondary-hover':  'var(--color-gray-600)',
        'action-secondary-text':   'var(--color-gray-300)',
        'action-destructive':      'var(--color-amber-700)',
        'state-urgent':            'var(--color-slate-500)',
        'state-moderate':          'var(--color-gray-400)',
        'state-low':               'var(--color-gray-600)',
        'state-success':           'var(--color-green-600)',
        'state-focus':             'var(--color-navy-900)',
        'ambient-calm':            'var(--color-gray-800)',
        'ambient-building':        'var(--color-navy-700)',
        'ambient-heavy':           'var(--color-navy-900)',
      },
      borderRadius: {
        'none': '0px',
        'sm':   '4px',
        'md':   '6px',
        'lg':   '8px',
        'xl':   '12px',
        '2xl':  '16px',
        'full': '9999px',
      },
      boxShadow: {
        'sm':   '0 1px 2px rgba(0,0,0,0.4)',
        'md':   '0 2px 8px rgba(0,0,0,0.5)',
        'lg':   '0 4px 16px rgba(0,0,0,0.6)',
        'glow': '0 0 20px rgba(69,123,157,0.15)',
      },
      fontSize: {
        'xs':   ['11px', { lineHeight: '1.5' }],
        'sm':   ['12px', { lineHeight: '1.5' }],
        'base': ['14px', { lineHeight: '1.5' }],
        'md':   ['15px', { lineHeight: '1.5' }],
        'lg':   ['16px', { lineHeight: '1.5' }],
        'xl':   ['18px', { lineHeight: '1.35' }],
        '2xl':  ['20px', { lineHeight: '1.35' }],
        '3xl':  ['24px', { lineHeight: '1.2' }],
        '4xl':  ['28px', { lineHeight: '1.2' }],
        '5xl':  ['32px', { lineHeight: '1.2' }],
      },
      letterSpacing: {
        'tight':   '-0.04em',
        'snug':    '-0.02em',
        'normal':  '0em',
        'wide':    '0.02em',
        'widest':  '0.1em',
      },
      variables: {
        DEFAULT: {
          colors: {
            black:       '#000000',
            white:       '#FFFFFF',
            'gray-950':  '#0A0A0A',
            'gray-900':  '#111111',
            'gray-800':  '#1A1A1A',
            'gray-700':  '#2A2A2A',
            'gray-600':  '#3A3A3A',
            'gray-500':  '#6B6B6B',
            'gray-400':  '#BCBBC0',
            'gray-300':  '#D4D4D4',
            'gray-200':  '#E8E8E8',
            'gray-100':  '#F4F4F4',
            'gray-50':   '#FAFAFA',
            'navy-900':  '#1D3557',
            'navy-700':  '#2E4F7A',
            'slate-500': '#457B9D',
            'slate-300': '#A8C4D8',
            'green-600': '#2A7A4B',
            'green-100': '#E6F4EC',
            'amber-700': '#7A3B1E',
            'amber-100': '#FDF6EC',
          },
        },
      },
    },
  },
  plugins: [
    require('@mertasan/tailwindcss-variables'),
  ],
}
